### ISSUE TITLE
[Feature Request] Advanced metrics support

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-python#369]
### Describe the solution you'd like

With https://github.com/temporalio/sdk-core/pull/544 landed, we need to:

* [x] Support any missing prom options (done in #380)
* [x] Support any missing otel options (done in #380)
* [ ] Support user-accessible metric buffer-based forwarding
* ~Support Python provided metric implementation~ We're gonna consider this too expensive at this time and not write this
* [x] Support access to metrics from runtime (done in #384)
* [x] Support access to metrics from activity with default activity tags (done in #384)
* [x] Support access to metrics from workflow with default workflow tags and ignore metric updates during replay by default (done in #384)
